# Generated by Django 2.0.5 on 2018-09-30 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('INTO', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('codigo_tipo_usuario', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('tipo_usuario', models.CharField(max_length=25)),
                ('descripcion_tipo_usuario', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='alumno',
            name='tipo_usuario',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='INTO.TipoUsuario'),
        ),
        migrations.AddField(
            model_name='docente',
            name='tipo_usuario',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='INTO.TipoUsuario'),
        ),
    ]
