# Generated by Django 2.0.5 on 2019-01-08 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('INTO', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='especialidad_alumno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='INTO.Especialidad'),
        ),
    ]
