# Generated by Django 2.0.5 on 2019-01-21 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INTO', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacion',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
