# Generated by Django 2.0.5 on 2018-10-12 04:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('INTO', '0002_auto_20180930_0020'),
    ]

    operations = [
        migrations.CreateModel(
            name='asignacionTipoUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='INTO.TipoUsuario')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='tipo_usuario',
        ),
        migrations.RemoveField(
            model_name='docente',
            name='tipo_usuario',
        ),
        migrations.AlterUniqueTogether(
            name='asignaciontipousuario',
            unique_together={('usuario', 'tipo_usuario')},
        ),
    ]
