# Generated by Django 2.0.5 on 2018-11-02 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INTO', '0002_auto_20181102_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='telefono_docente',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
