# Generated by Django 2.0.5 on 2019-01-19 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INTO', '0002_auto_20190118_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente_materia_grupo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
