# Generated by Django 2.0.5 on 2019-01-19 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INTO', '0003_auto_20190118_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anotacion',
            name='descripcion',
            field=models.CharField(max_length=1500),
        ),
    ]
