# Generated by Django 2.0.5 on 2019-01-08 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('INTO', '0003_auto_20190108_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialidad_materia',
            name='codigo_materia',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='INTO.Materia'),
        ),
    ]
