# Generated by Django 2.0.5 on 2018-11-03 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('INTO', '0003_auto_20181102_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anotacion',
            fields=[
                ('codigo_anotacion', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=150)),
                ('fecha_anotacion', models.DateField()),
                ('dui_docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='INTO.Docente')),
                ('nie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='INTO.Alumno')),
            ],
        ),
    ]
