# Generated by Django 2.0.5 on 2019-01-19 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('INTO', '0004_auto_20190119_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno_grupo',
            name='nie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='INTO.Alumno'),
        ),
    ]
