# Generated by Django 2.0.5 on 2019-01-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INTO', '0004_anotacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='anio_ingreso',
            field=models.IntegerField(),
        ),
    ]
