# Generated by Django 2.0.5 on 2019-01-08 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('INTO', '0004_auto_20190108_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialidad_materia',
            name='codigo_especialidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='INTO.Especialidad'),
        ),
        migrations.AlterField(
            model_name='especialidad_materia',
            name='codigo_materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='INTO.Materia'),
        ),
    ]
