# Generated by Django 2.0.5 on 2019-01-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INTO', '0005_auto_20190107_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='anio_ingreso',
            field=models.DateField(),
        ),
    ]
