# Generated by Django 2.0.5 on 2018-09-25 03:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('codigo_actividad', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('tipo_actividad', models.CharField(help_text='Ingrese el tipo de actividad, por ejemplo si es examen o exposicion', max_length=25)),
                ('categoria_actividad', models.IntegerField()),
                ('porcentaje_actividad', models.DecimalField(decimal_places=4, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('codigo_alumno', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre_alumno', models.CharField(max_length=50)),
                ('apellidos_alumno', models.CharField(max_length=50)),
                ('fecha_nacimiento_alumno', models.DateField()),
                ('telefono_alumno', models.CharField(max_length=9, null=True)),
                ('direccion_alumno', models.CharField(max_length=50, null=True)),
                ('sexo_alumno', models.CharField(max_length=5)),
                ('año_ingreso', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Alumno_Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promedio_actividad_alumno', models.DecimalField(decimal_places=4, max_digits=4)),
                ('codigo_actividad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='INTO.Actividad')),
                ('codigo_alumno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='INTO.Alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Alumno_AnioLectivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promedio_año_lectivo', models.DecimalField(decimal_places=4, max_digits=4)),
                ('aprobado', models.BooleanField()),
                ('codigo_alumno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='INTO.Alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Alumno_Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.IntegerField(help_text='Año en el cual el alumno esta en ese grupo')),
                ('codigo_alumno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='INTO.Alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Alumno_Periodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promedio_periodo_alumno', models.DecimalField(decimal_places=4, max_digits=4)),
                ('codigo_alumno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='INTO.Alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Alumno_Sub_Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje_obtenido', models.DecimalField(decimal_places=4, help_text='Nota*PorcentajeEvaSubActividad', max_digits=4)),
                ('codigo_actividad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='INTO.Actividad')),
                ('codigo_alumno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='INTO.Alumno')),
            ],
        ),
        migrations.CreateModel(
            name='AnioLectivo',
            fields=[
                ('año_lectivo', models.IntegerField(primary_key=True, serialize=False)),
                ('terminado', models.BooleanField(help_text='Indica si el año escolar ya ha finalizado')),
            ],
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(decimal_places=4, max_digits=4)),
                ('codigo_alumno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='INTO.Alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('dui_docente', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombre_docente', models.CharField(max_length=50)),
                ('apellidos_docente', models.CharField(max_length=50)),
                ('fecha_nacimiento_docente', models.DateField()),
                ('telefono_docente', models.CharField(max_length=9, null=True)),
                ('email_docente', models.EmailField(max_length=254)),
                ('fecha_contratacion_docente', models.DateField(null=True)),
                ('direccion_docente', models.CharField(max_length=50, null=True)),
                ('usuario_docente', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('codigo_especialidad', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre_especialidad', models.CharField(max_length=50)),
                ('descripcion_especialidad', models.CharField(max_length=150, null=True)),
                ('años_especialidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Especialidad_Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_materia', models.IntegerField()),
                ('codigo_especialidad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='INTO.Especialidad')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('codigo_evaluacion', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombre_evaluacion', models.CharField(max_length=50)),
                ('categoria_evaluacion', models.IntegerField()),
                ('porcentaje_sub_actividad', models.DecimalField(decimal_places=4, max_digits=5)),
                ('descripcion_evaluacion', models.CharField(max_length=150, null=True)),
                ('codigo_docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='INTO.Docente')),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('codigo_grupo', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nivel', models.IntegerField(help_text='Ingrese el nivel de la especialidad de este grupo')),
                ('seccion', models.CharField(max_length=8)),
                ('codigo_docente_encargado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='INTO.Docente')),
                ('codigo_especialidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='INTO.Especialidad')),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('codigo_materia', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombre_materia', models.CharField(max_length=30)),
                ('descripcion_materia', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('codigo_periodo', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('finalizado', models.BooleanField(help_text='Indica si el periodo ya ha finalizado')),
                ('año_lectivo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='INTO.AnioLectivo')),
            ],
        ),
        migrations.CreateModel(
            name='Sub_Actividad',
            fields=[
                ('codigo_sub_actividad', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('porcentaje_sub_actividad', models.DecimalField(decimal_places=4, max_digits=5)),
                ('descripcion_sub_actividad', models.CharField(max_length=150, null=True)),
                ('codigo_actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='INTO.Actividad')),
            ],
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='codigo_materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='INTO.Materia'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='codigo_sub_actividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='INTO.Sub_Actividad'),
        ),
        migrations.AddField(
            model_name='especialidad_materia',
            name='codigo_materia',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='INTO.Materia'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='codigo_evaluacion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='INTO.Evaluacion'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='codigo_materia',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='INTO.Materia'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='codigo_sub_actividad',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='INTO.Sub_Actividad'),
        ),
        migrations.AddField(
            model_name='alumno_sub_actividad',
            name='codigo_materia',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='INTO.Materia'),
        ),
        migrations.AddField(
            model_name='alumno_sub_actividad',
            name='codigo_sub_actividad',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='INTO.Sub_Actividad'),
        ),
        migrations.AddField(
            model_name='alumno_periodo',
            name='codigo_año_lectivo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='INTO.AnioLectivo'),
        ),
        migrations.AddField(
            model_name='alumno_periodo',
            name='codigo_materia',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='INTO.Materia'),
        ),
        migrations.AddField(
            model_name='alumno_periodo',
            name='codigo_periodo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='INTO.Periodo'),
        ),
        migrations.AddField(
            model_name='alumno_grupo',
            name='codigo_grupo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='INTO.Grupo'),
        ),
        migrations.AddField(
            model_name='alumno_aniolectivo',
            name='codigo_año_lectivo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='INTO.AnioLectivo'),
        ),
        migrations.AddField(
            model_name='alumno_aniolectivo',
            name='codigo_materia',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='INTO.Materia'),
        ),
        migrations.AddField(
            model_name='alumno_actividad',
            name='codigo_materia',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='INTO.Materia'),
        ),
        migrations.AddField(
            model_name='alumno_actividad',
            name='codigo_periodo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='INTO.Periodo'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='especialidad_alumno',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='INTO.Especialidad'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='usuario_alumno',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actividad',
            name='codigo_periodo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='INTO.Periodo'),
        ),
    ]
